# Pandas

In [63]:
import pandas
import numpy

In [64]:
df=pd.DataFrame()


NameError: name 'pd' is not defined

In [ ]:
df.isnull().sum()   #counting sum of all null values in columns

In [ ]:
df['Column1'].unique()

# Numpy

In [ ]:
import numpy as np

In [ ]:
list1=[1,4,2,5,9]

In [ ]:
arr=np.array(list1)

In [ ]:
print(arr)

In [ ]:
list2=[8,9,6,10,99]

In [65]:
arr=np.array([list1,list2])

In [66]:
print(arr)

[[ 1  4  2  5  9]
 [ 8  9  6 10 99]]


In [67]:
arr.shape

(2, 5)

In [68]:
ar=arr
ar

array([[ 1,  4,  2,  5,  9],
       [ 8,  9,  6, 10, 99]])

In [69]:
ar.reshape(10,1)
print(ar)

[[ 1  4  2  5  9]
 [ 8  9  6 10 99]]


## Indexing

In [16]:
arr[1,4]

99

In [17]:
arr[::]

array([[ 1,  4,  2,  5,  9],
       [ 8,  9,  6, 10, 99]])

In [ ]:
arr[0:2,0:2]

## Arrange 

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Copy and broadcasting

In [38]:
arr2=arr

In [39]:
arr2[1:]=5000

In [40]:
arr2

array([[   1,    4,    2,    5,    9],
       [5000, 5000, 5000, 5000, 5000]])

In [41]:
arr3=arr

In [42]:
arr3

array([[   1,    4,    2,    5,    9],
       [5000, 5000, 5000, 5000, 5000]])

## Conditions

In [51]:
arr3[arr3<5]

array([1, 4, 2])

### Ones

In [52]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [54]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Random

In [57]:
np.random.rand(3,3)   # random values bw 0 to 1

array([[0.79927663, 0.09604624, 0.41027416],
       [0.26122001, 0.44568386, 0.29938591],
       [0.20955012, 0.23381008, 0.90674935]])

#### Use shift+tab after the function, before brackets to see the functioning

In [58]:
np.random.randn(3,3)  # standard normal distribution

array([[-0.32060179, -0.219381  , -0.11490551],
       [ 0.80341052, -0.94301108, -1.67909074],
       [-1.22674604,  0.00298136,  0.94723532]])

In [59]:
np.random.randint(0,100,8)   # from 0 to 100 select 8 numbers

array([44, 16, 95,  4, 21, 21, 73, 79])

In [60]:
np.random.randint(0,100,8).reshape(2,4)

array([[24,  1, 99, 17],
       [37, 27, 65, 20]])

In [62]:
np.random.random_sample((1,5))   

array([[0.41414702, 0.20230668, 0.59717974, 0.09376077, 0.62573008]])